//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationManager.ServiceReferenceRdv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRdv.IRdvService")]
    public interface IRdvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetAllRdv", ReplyAction="http://tempuri.org/IRdvService/GetAllRdvResponse")]
        ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetAllRdv(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetAllRdv", ReplyAction="http://tempuri.org/IRdvService/GetAllRdvResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetAllRdvAsync(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetRdvMedecin", ReplyAction="http://tempuri.org/IRdvService/GetRdvMedecinResponse")]
        ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetRdvMedecin(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetRdvMedecin", ReplyAction="http://tempuri.org/IRdvService/GetRdvMedecinResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetRdvMedecinAsync(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetRdvConsultation", ReplyAction="http://tempuri.org/IRdvService/GetRdvConsultationResponse")]
        ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetRdvConsultation(string idConsultation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/GetRdvConsultation", ReplyAction="http://tempuri.org/IRdvService/GetRdvConsultationResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetRdvConsultationAsync(string idConsultation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/AddRdv", ReplyAction="http://tempuri.org/IRdvService/AddRdvResponse")]
        ConsultationManagerServer.Models.RDV AddRdv(ConsultationManagerServer.Models.RDV rdv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/AddRdv", ReplyAction="http://tempuri.org/IRdvService/AddRdvResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.RDV> AddRdvAsync(ConsultationManagerServer.Models.RDV rdv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/UpdateRdv", ReplyAction="http://tempuri.org/IRdvService/UpdateRdvResponse")]
        ConsultationManagerServer.Models.RDV UpdateRdv(ConsultationManagerServer.Models.RDV rdv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRdvService/UpdateRdv", ReplyAction="http://tempuri.org/IRdvService/UpdateRdvResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.RDV> UpdateRdvAsync(ConsultationManagerServer.Models.RDV rdv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRdvServiceChannel : ConsultationManager.ServiceReferenceRdv.IRdvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RdvServiceClient : System.ServiceModel.ClientBase<ConsultationManager.ServiceReferenceRdv.IRdvService>, ConsultationManager.ServiceReferenceRdv.IRdvService {
        
        public RdvServiceClient() {
        }
        
        public RdvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RdvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RdvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RdvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetAllRdv(string idService) {
            return base.Channel.GetAllRdv(idService);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetAllRdvAsync(string idService) {
            return base.Channel.GetAllRdvAsync(idService);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetRdvMedecin(string idMedecin) {
            return base.Channel.GetRdvMedecin(idMedecin);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetRdvMedecinAsync(string idMedecin) {
            return base.Channel.GetRdvMedecinAsync(idMedecin);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[] GetRdvConsultation(string idConsultation) {
            return base.Channel.GetRdvConsultation(idConsultation);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.RdvPatientMedecin[]> GetRdvConsultationAsync(string idConsultation) {
            return base.Channel.GetRdvConsultationAsync(idConsultation);
        }
        
        public ConsultationManagerServer.Models.RDV AddRdv(ConsultationManagerServer.Models.RDV rdv) {
            return base.Channel.AddRdv(rdv);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.RDV> AddRdvAsync(ConsultationManagerServer.Models.RDV rdv) {
            return base.Channel.AddRdvAsync(rdv);
        }
        
        public ConsultationManagerServer.Models.RDV UpdateRdv(ConsultationManagerServer.Models.RDV rdv) {
            return base.Channel.UpdateRdv(rdv);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.RDV> UpdateRdvAsync(ConsultationManagerServer.Models.RDV rdv) {
            return base.Channel.UpdateRdvAsync(rdv);
        }
    }
}
