//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationManager.ServiceReferencePathologie {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePathologie.IPathologieService")]
    public interface IPathologieService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/GetServiceDetails", ReplyAction="http://tempuri.org/IPathologieService/GetServiceDetailsResponse")]
        ConsultationManagerServer.Models.SerializedModels.ServicePathologies GetServiceDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/GetServiceDetails", ReplyAction="http://tempuri.org/IPathologieService/GetServiceDetailsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.ServicePathologies> GetServiceDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/AddPathologie", ReplyAction="http://tempuri.org/IPathologieService/AddPathologieResponse")]
        ConsultationManagerServer.Models.Pathologie AddPathologie(ConsultationManagerServer.Models.Pathologie pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/AddPathologie", ReplyAction="http://tempuri.org/IPathologieService/AddPathologieResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Pathologie> AddPathologieAsync(ConsultationManagerServer.Models.Pathologie pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/UpdatePathologie", ReplyAction="http://tempuri.org/IPathologieService/UpdatePathologieResponse")]
        ConsultationManagerServer.Models.Pathologie UpdatePathologie(string id, ConsultationManagerServer.Models.Pathologie pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/UpdatePathologie", ReplyAction="http://tempuri.org/IPathologieService/UpdatePathologieResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Pathologie> UpdatePathologieAsync(string id, ConsultationManagerServer.Models.Pathologie pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/UpdateService", ReplyAction="http://tempuri.org/IPathologieService/UpdateServiceResponse")]
        ConsultationManagerServer.Models.Service UpdateService(string id, ConsultationManagerServer.Models.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/UpdateService", ReplyAction="http://tempuri.org/IPathologieService/UpdateServiceResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Service> UpdateServiceAsync(string id, ConsultationManagerServer.Models.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/DeletePathologie", ReplyAction="http://tempuri.org/IPathologieService/DeletePathologieResponse")]
        void DeletePathologie(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathologieService/DeletePathologie", ReplyAction="http://tempuri.org/IPathologieService/DeletePathologieResponse")]
        System.Threading.Tasks.Task DeletePathologieAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPathologieServiceChannel : ConsultationManager.ServiceReferencePathologie.IPathologieService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PathologieServiceClient : System.ServiceModel.ClientBase<ConsultationManager.ServiceReferencePathologie.IPathologieService>, ConsultationManager.ServiceReferencePathologie.IPathologieService {
        
        public PathologieServiceClient() {
        }
        
        public PathologieServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PathologieServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathologieServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathologieServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsultationManagerServer.Models.SerializedModels.ServicePathologies GetServiceDetails() {
            return base.Channel.GetServiceDetails();
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.ServicePathologies> GetServiceDetailsAsync() {
            return base.Channel.GetServiceDetailsAsync();
        }
        
        public ConsultationManagerServer.Models.Pathologie AddPathologie(ConsultationManagerServer.Models.Pathologie pathologie) {
            return base.Channel.AddPathologie(pathologie);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Pathologie> AddPathologieAsync(ConsultationManagerServer.Models.Pathologie pathologie) {
            return base.Channel.AddPathologieAsync(pathologie);
        }
        
        public ConsultationManagerServer.Models.Pathologie UpdatePathologie(string id, ConsultationManagerServer.Models.Pathologie pathologie) {
            return base.Channel.UpdatePathologie(id, pathologie);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Pathologie> UpdatePathologieAsync(string id, ConsultationManagerServer.Models.Pathologie pathologie) {
            return base.Channel.UpdatePathologieAsync(id, pathologie);
        }
        
        public ConsultationManagerServer.Models.Service UpdateService(string id, ConsultationManagerServer.Models.Service service) {
            return base.Channel.UpdateService(id, service);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Service> UpdateServiceAsync(string id, ConsultationManagerServer.Models.Service service) {
            return base.Channel.UpdateServiceAsync(id, service);
        }
        
        public void DeletePathologie(string id) {
            base.Channel.DeletePathologie(id);
        }
        
        public System.Threading.Tasks.Task DeletePathologieAsync(string id) {
            return base.Channel.DeletePathologieAsync(id);
        }
    }
}
