//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationManager.ServiceReferenceConsultation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceConsultation.IConsultationService")]
    public interface IConsultationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/GetServiceDetails", ReplyAction="http://tempuri.org/IConsultationService/GetServiceDetailsResponse")]
        ConsultationManagerServer.Models.SerializedModels.ServicePathologies GetServiceDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/GetServiceDetails", ReplyAction="http://tempuri.org/IConsultationService/GetServiceDetailsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.ServicePathologies> GetServiceDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/AddConsultation", ReplyAction="http://tempuri.org/IConsultationService/AddConsultationResponse")]
        ConsultationManagerServer.Models.Consultation AddConsultation(ConsultationManagerServer.Models.Consultation pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/AddConsultation", ReplyAction="http://tempuri.org/IConsultationService/AddConsultationResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Consultation> AddConsultationAsync(ConsultationManagerServer.Models.Consultation pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/UpdateConsultation", ReplyAction="http://tempuri.org/IConsultationService/UpdateConsultationResponse")]
        ConsultationManagerServer.Models.Consultation UpdateConsultation(string id, ConsultationManagerServer.Models.Consultation pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/UpdateConsultation", ReplyAction="http://tempuri.org/IConsultationService/UpdateConsultationResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Consultation> UpdateConsultationAsync(string id, ConsultationManagerServer.Models.Consultation pathologie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/UpdateService", ReplyAction="http://tempuri.org/IConsultationService/UpdateServiceResponse")]
        ConsultationManagerServer.Models.Service UpdateService(string id, ConsultationManagerServer.Models.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/UpdateService", ReplyAction="http://tempuri.org/IConsultationService/UpdateServiceResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Service> UpdateServiceAsync(string id, ConsultationManagerServer.Models.Service service);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/DeleteConsultation", ReplyAction="http://tempuri.org/IConsultationService/DeleteConsultationResponse")]
        void DeleteConsultation(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultationService/DeleteConsultation", ReplyAction="http://tempuri.org/IConsultationService/DeleteConsultationResponse")]
        System.Threading.Tasks.Task DeleteConsultationAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultationServiceChannel : ConsultationManager.ServiceReferenceConsultation.IConsultationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultationServiceClient : System.ServiceModel.ClientBase<ConsultationManager.ServiceReferenceConsultation.IConsultationService>, ConsultationManager.ServiceReferenceConsultation.IConsultationService {
        
        public ConsultationServiceClient() {
        }
        
        public ConsultationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsultationManagerServer.Models.SerializedModels.ServicePathologies GetServiceDetails() {
            return base.Channel.GetServiceDetails();
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.ServicePathologies> GetServiceDetailsAsync() {
            return base.Channel.GetServiceDetailsAsync();
        }
        
        public ConsultationManagerServer.Models.Consultation AddConsultation(ConsultationManagerServer.Models.Consultation pathologie) {
            return base.Channel.AddConsultation(pathologie);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Consultation> AddConsultationAsync(ConsultationManagerServer.Models.Consultation pathologie) {
            return base.Channel.AddConsultationAsync(pathologie);
        }
        
        public ConsultationManagerServer.Models.Consultation UpdateConsultation(string id, ConsultationManagerServer.Models.Consultation pathologie) {
            return base.Channel.UpdateConsultation(id, pathologie);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Consultation> UpdateConsultationAsync(string id, ConsultationManagerServer.Models.Consultation pathologie) {
            return base.Channel.UpdateConsultationAsync(id, pathologie);
        }
        
        public ConsultationManagerServer.Models.Service UpdateService(string id, ConsultationManagerServer.Models.Service service) {
            return base.Channel.UpdateService(id, service);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Service> UpdateServiceAsync(string id, ConsultationManagerServer.Models.Service service) {
            return base.Channel.UpdateServiceAsync(id, service);
        }
        
        public void DeleteConsultation(string id) {
            base.Channel.DeleteConsultation(id);
        }
        
        public System.Threading.Tasks.Task DeleteConsultationAsync(string id) {
            return base.Channel.DeleteConsultationAsync(id);
        }
    }
}
