//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationManager.ServiceReferenceDossierMed {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDossierMed.IDossierMedService")]
    public interface IDossierMedService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetAllDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetAllDossierMedsResponse")]
        ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetAllDossierMeds(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetAllDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetAllDossierMedsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetAllDossierMedsAsync(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetConsultDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetConsultDossierMedsResponse")]
        ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetConsultDossierMeds(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetConsultDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetConsultDossierMedsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetConsultDossierMedsAsync(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetMedecinDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetMedecinDossierMedsResponse")]
        ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetMedecinDossierMeds(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetMedecinDossierMeds", ReplyAction="http://tempuri.org/IDossierMedService/GetMedecinDossierMedsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetMedecinDossierMedsAsync(string idMedecin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/GetDossierMedResponse")]
        ConsultationManagerServer.Models.SerializedModels.DossierMedDetail GetDossierMed(string idPatient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/GetDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/GetDossierMedResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail> GetDossierMedAsync(string idPatient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/AddDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/AddDossierMedResponse")]
        ConsultationManagerServer.Models.DossierMed AddDossierMed(ConsultationManagerServer.Models.DossierMed dossierMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/AddDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/AddDossierMedResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.DossierMed> AddDossierMedAsync(ConsultationManagerServer.Models.DossierMed dossierMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/UpdateDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/UpdateDossierMedResponse")]
        ConsultationManagerServer.Models.DossierMed UpdateDossierMed(ConsultationManagerServer.Models.DossierMed dossierMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/UpdateDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/UpdateDossierMedResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.DossierMed> UpdateDossierMedAsync(ConsultationManagerServer.Models.DossierMed dossierMed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/DeleteDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/DeleteDossierMedResponse")]
        void DeleteDossierMed(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDossierMedService/DeleteDossierMed", ReplyAction="http://tempuri.org/IDossierMedService/DeleteDossierMedResponse")]
        System.Threading.Tasks.Task DeleteDossierMedAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDossierMedServiceChannel : ConsultationManager.ServiceReferenceDossierMed.IDossierMedService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DossierMedServiceClient : System.ServiceModel.ClientBase<ConsultationManager.ServiceReferenceDossierMed.IDossierMedService>, ConsultationManager.ServiceReferenceDossierMed.IDossierMedService {
        
        public DossierMedServiceClient() {
        }
        
        public DossierMedServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DossierMedServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DossierMedServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DossierMedServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetAllDossierMeds(string idService) {
            return base.Channel.GetAllDossierMeds(idService);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetAllDossierMedsAsync(string idService) {
            return base.Channel.GetAllDossierMedsAsync(idService);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetConsultDossierMeds(string idMedecin) {
            return base.Channel.GetConsultDossierMeds(idMedecin);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetConsultDossierMedsAsync(string idMedecin) {
            return base.Channel.GetConsultDossierMedsAsync(idMedecin);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[] GetMedecinDossierMeds(string idMedecin) {
            return base.Channel.GetMedecinDossierMeds(idMedecin);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail[]> GetMedecinDossierMedsAsync(string idMedecin) {
            return base.Channel.GetMedecinDossierMedsAsync(idMedecin);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.DossierMedDetail GetDossierMed(string idPatient) {
            return base.Channel.GetDossierMed(idPatient);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DossierMedDetail> GetDossierMedAsync(string idPatient) {
            return base.Channel.GetDossierMedAsync(idPatient);
        }
        
        public ConsultationManagerServer.Models.DossierMed AddDossierMed(ConsultationManagerServer.Models.DossierMed dossierMed) {
            return base.Channel.AddDossierMed(dossierMed);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.DossierMed> AddDossierMedAsync(ConsultationManagerServer.Models.DossierMed dossierMed) {
            return base.Channel.AddDossierMedAsync(dossierMed);
        }
        
        public ConsultationManagerServer.Models.DossierMed UpdateDossierMed(ConsultationManagerServer.Models.DossierMed dossierMed) {
            return base.Channel.UpdateDossierMed(dossierMed);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.DossierMed> UpdateDossierMedAsync(ConsultationManagerServer.Models.DossierMed dossierMed) {
            return base.Channel.UpdateDossierMedAsync(dossierMed);
        }
        
        public void DeleteDossierMed(string id) {
            base.Channel.DeleteDossierMed(id);
        }
        
        public System.Threading.Tasks.Task DeleteDossierMedAsync(string id) {
            return base.Channel.DeleteDossierMedAsync(id);
        }
    }
}
