//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultationManager.ServiceReferenceHospit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceHospit.IHospitService")]
    public interface IHospitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddHospit", ReplyAction="http://tempuri.org/IHospitService/AddHospitResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Hospitalisation AddHospit(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation hospit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddHospit", ReplyAction="http://tempuri.org/IHospitService/AddHospitResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Hospitalisation> AddHospitAsync(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation hospit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesurePoids", ReplyAction="http://tempuri.org/IHospitService/AddMesurePoidsResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesurePoids(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesurePoids", ReplyAction="http://tempuri.org/IHospitService/AddMesurePoidsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesurePoidsAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureTa", ReplyAction="http://tempuri.org/IHospitService/AddMesureTaResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureTa(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureTa", ReplyAction="http://tempuri.org/IHospitService/AddMesureTaResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureTaAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureTemperature", ReplyAction="http://tempuri.org/IHospitService/AddMesureTemperatureResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureTemperature(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureTemperature", ReplyAction="http://tempuri.org/IHospitService/AddMesureTemperatureResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureTemperatureAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureGlycemique", ReplyAction="http://tempuri.org/IHospitService/AddMesureGlycemiqueResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureGlycemique(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddMesureGlycemique", ReplyAction="http://tempuri.org/IHospitService/AddMesureGlycemiqueResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureGlycemiqueAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddIntervention", ReplyAction="http://tempuri.org/IHospitService/AddInterventionResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Intervention AddIntervention(ConsultationManagerServer.Models.Hospitalisations.Intervention interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/AddIntervention", ReplyAction="http://tempuri.org/IHospitService/AddInterventionResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Intervention> AddInterventionAsync(ConsultationManagerServer.Models.Hospitalisations.Intervention interv, string[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetDemandesHospit", ReplyAction="http://tempuri.org/IHospitService/GetDemandesHospitResponse")]
        ConsultationManagerServer.Models.SerializedModels.DemandeHospitDetail[] GetDemandesHospit(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetDemandesHospit", ReplyAction="http://tempuri.org/IHospitService/GetDemandesHospitResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DemandeHospitDetail[]> GetDemandesHospitAsync(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetHospit", ReplyAction="http://tempuri.org/IHospitService/GetHospitResponse")]
        ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail GetHospit(string idConclus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetHospit", ReplyAction="http://tempuri.org/IHospitService/GetHospitResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail> GetHospitAsync(string idConclus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetHospits", ReplyAction="http://tempuri.org/IHospitService/GetHospitsResponse")]
        ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail[] GetHospits(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetHospits", ReplyAction="http://tempuri.org/IHospitService/GetHospitsResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail[]> GetHospitsAsync(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetSallePlanning", ReplyAction="http://tempuri.org/IHospitService/GetSallePlanningResponse")]
        ConsultationManagerServer.Models.SerializedModels.SalleHospitPlanning[] GetSallePlanning(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/GetSallePlanning", ReplyAction="http://tempuri.org/IHospitService/GetSallePlanningResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.SalleHospitPlanning[]> GetSallePlanningAsync(string idService);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/UpdateHospit", ReplyAction="http://tempuri.org/IHospitService/UpdateHospitResponse")]
        ConsultationManagerServer.Models.Hospitalisations.Hospitalisation UpdateHospit(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation salle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/UpdateHospit", ReplyAction="http://tempuri.org/IHospitService/UpdateHospitResponse")]
        System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Hospitalisation> UpdateHospitAsync(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation salle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/DeleteHospit", ReplyAction="http://tempuri.org/IHospitService/DeleteHospitResponse")]
        void DeleteHospit(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHospitService/DeleteHospit", ReplyAction="http://tempuri.org/IHospitService/DeleteHospitResponse")]
        System.Threading.Tasks.Task DeleteHospitAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHospitServiceChannel : ConsultationManager.ServiceReferenceHospit.IHospitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HospitServiceClient : System.ServiceModel.ClientBase<ConsultationManager.ServiceReferenceHospit.IHospitService>, ConsultationManager.ServiceReferenceHospit.IHospitService {
        
        public HospitServiceClient() {
        }
        
        public HospitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HospitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HospitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Hospitalisation AddHospit(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation hospit) {
            return base.Channel.AddHospit(hospit);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Hospitalisation> AddHospitAsync(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation hospit) {
            return base.Channel.AddHospitAsync(hospit);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesurePoids(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesurePoids(interv, ids);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesurePoidsAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesurePoidsAsync(interv, ids);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureTa(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureTa(interv, ids);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureTaAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureTaAsync(interv, ids);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureTemperature(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureTemperature(interv, ids);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureTemperatureAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureTemperatureAsync(interv, ids);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Mesure AddMesureGlycemique(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureGlycemique(interv, ids);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Mesure> AddMesureGlycemiqueAsync(ConsultationManagerServer.Models.Hospitalisations.Mesure interv, string[] ids) {
            return base.Channel.AddMesureGlycemiqueAsync(interv, ids);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Intervention AddIntervention(ConsultationManagerServer.Models.Hospitalisations.Intervention interv, string[] ids) {
            return base.Channel.AddIntervention(interv, ids);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Intervention> AddInterventionAsync(ConsultationManagerServer.Models.Hospitalisations.Intervention interv, string[] ids) {
            return base.Channel.AddInterventionAsync(interv, ids);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.DemandeHospitDetail[] GetDemandesHospit(string idService) {
            return base.Channel.GetDemandesHospit(idService);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.DemandeHospitDetail[]> GetDemandesHospitAsync(string idService) {
            return base.Channel.GetDemandesHospitAsync(idService);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail GetHospit(string idConclus) {
            return base.Channel.GetHospit(idConclus);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail> GetHospitAsync(string idConclus) {
            return base.Channel.GetHospitAsync(idConclus);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail[] GetHospits(string idService) {
            return base.Channel.GetHospits(idService);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.HospitalisationDetail[]> GetHospitsAsync(string idService) {
            return base.Channel.GetHospitsAsync(idService);
        }
        
        public ConsultationManagerServer.Models.SerializedModels.SalleHospitPlanning[] GetSallePlanning(string idService) {
            return base.Channel.GetSallePlanning(idService);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.SerializedModels.SalleHospitPlanning[]> GetSallePlanningAsync(string idService) {
            return base.Channel.GetSallePlanningAsync(idService);
        }
        
        public ConsultationManagerServer.Models.Hospitalisations.Hospitalisation UpdateHospit(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation salle) {
            return base.Channel.UpdateHospit(salle);
        }
        
        public System.Threading.Tasks.Task<ConsultationManagerServer.Models.Hospitalisations.Hospitalisation> UpdateHospitAsync(ConsultationManagerServer.Models.Hospitalisations.Hospitalisation salle) {
            return base.Channel.UpdateHospitAsync(salle);
        }
        
        public void DeleteHospit(string id) {
            base.Channel.DeleteHospit(id);
        }
        
        public System.Threading.Tasks.Task DeleteHospitAsync(string id) {
            return base.Channel.DeleteHospitAsync(id);
        }
    }
}
